export enum NotificationType {
  // Ride
  RIDE_REQUESTED = "RIDE_REQUESTED",
  RIDE_ACCEPTED = "RIDE_ACCEPTED",
  RIDE_ARRIVED = "RIDE_ARRIVED",
  RIDE_REJECTED = "RIDE_REJECTED",
  RIDE_STARTED = "RIDE_STARTED",
  RIDE_COMPLETED = "RIDE_COMPLETED",
  RIDE_CANCELLED = "RIDE_CANCELLED",

  RIDE_CANCELLED_BY_DRIVER = "RIDE_CANCELLED_BY_DRIVER",

  // Payment
  PAYMENT_INITIATED = "PAYMENT_INITIATED",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  PAYMENT_FAILED = "PAYMENT_FAILED",

  // Promotions
  PROMO_OFFER = "PROMO_OFFER",
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
}
