export enum NotificationType {
  // Ride
  RIDE_REQUESTED = "RIDE REQUESTED",
  RIDE_ACCEPTED = "RIDE ACCEPTED",
  RIDE_ARRIVED = "RIDE ARRIVED",
  RIDE_REJECTED = "RIDE REJECTED",
  RIDE_STARTED = "RIDE STARTED",
  RIDE_COMPLETED = "RIDE COMPLETED",
  RIDE_CANCELLED = "RIDE CANCELLED",
  RIDE_NO_DRIVER_FOUND = "NO_DRIVER FOUND",
  RIDE_CANCELLED_BY_DRIVER = "RIDE CANCELLED BY DRIVER",
  NO_DRIVER_ACCEPTED = "NO_DRIVER_ACCDPTED",
  RIDE_REQUEST_EXPIRED = "RIDE REQUEST EXPIRED",

  // Payment
  PAYMENT_INITIATED = "PAYMENT INITIATED",
  PAYMENT_COMPLETED = "PAYMENT COMPLETED",
  PAYMENT_FAILED = "PAYMENT FAILED",

  // Promotions
  PROMO_OFFER = "PROMO OFFER",
  SYSTEM_ANNOUNCEMENT = "SYSTEM ANNOUNCEMENT",

  NEW_MESSAGE = "NEW MESSAGE",
}
