export enum TransactionType {
  RIDE_PAYMENT = "RIDE_PAYMENT",
  DRIVER_EARNING = "DRIVER_EARNING",
  PLATFORM_COMMISSION = "PLATFORM_COMMISSION",
  RIDER_CANCELLATION_FEE = "RIDER CANCELLATION FEE",
  DRIVER_PENALTY_REVENUE = "DRIVER PENALTY REVENUE",

  DRIVER_BONUS = "DRIVER_BONUS",
  DRIVER_PENALTY = "DRIVER_PENALTY",

  REFUND = "REFUND",
  PAYOUT = "PAYOUT",
  WALLET_TOPUP = "WALLET_TOPUP",
  ADJUSTMENT = "ADJUSTMENT",
}
