// Container Symbols
export const TYPES = {
  // Repositories
  UserRepository: Symbol.for("UserRepository"),
  RefreshTokenRepository: Symbol.for("RefreshTokenRepository"),
  AdminUserRepository: Symbol.for("AdminUserRepository"),
  AdminDriverRepository: Symbol.for("AdminDriverRepository"),
  AdminKYCRepository: Symbol.for("AdminKYCRepository"),
  KYCRepository: Symbol.for("KYCRepository"),
  DriverRepository: Symbol.for("DriverRepository"),
  DriverAvailabilityRepository: Symbol.for("DriverAvailabilityRepository"),
  DriverDashboardRepository: Symbol.for("DriverDashboardRepository"),
  FareConfigurationRepository: Symbol.for("FareConfigurationRepository"),
  RideRequestRepository: Symbol.for("RideRequestRepository"),
  RideRepository: Symbol.for("RideRepository"),
  DriverLocationRepository: Symbol.for("DriverLocationRepository"),
  PaymentRepository: Symbol.for("PaymentRepository"),
  TransactionRepository: Symbol.for("TransactionRepository"),
  UnitOfWork: Symbol.for("IUnitOfWork"),
  PayoutRepository: Symbol.for("PayoutRepository"),
  WalletRepository: Symbol.for("WalletRepository"),
  RatingRepository: Symbol.for("RatingRepository"),
  CouponRepository: Symbol.for("CouponRepository"),
  CouponUsageRepository: Symbol.for("CouponUsageRepository"),
  RideRequestGroupRepository: Symbol.for("RideRequestGroupRepository"),
  ChatRoomRepository: Symbol.for("ChatRoomRepository"),
  MessageRepository: Symbol.for("MessageRepository"),
  MessageStatusRepository: Symbol.for("MessageStatusRepository"),
  UserChatRepository: Symbol.for("UserChatRepository"),
  FutureRideRequestRepository: Symbol.for("FutureRideRequestRepository"),

  // Application Services
  PasswordService: Symbol.for("PasswordService"),
  TokenService: Symbol.for("TokenService"),
  EmailService: Symbol.for("EmailService"),
  OtpService: Symbol.for("OtpService"),
  GoogleAuthService: Symbol.for("GoogleAuthService"),
  FileUploadService: Symbol.for("FileUploadService"),
  TokenManagementService: Symbol.for("TokenManagementService"),
  FareCalculationService: Symbol.for("FareCalculationService"),
  AvailabilityCheckService: Symbol.for("AvailabilityCheckService"),
  DistributedLockService: Symbol.for("DistributedLockService"),
  RideNotificationService: Symbol.for("RideNotificationService"),
  RedisService: Symbol.for("RedisService"),
  PaymentGatewayService: Symbol.for("PaymentGatewayService"),
  EarningsDistributionService: Symbol.for("EarningsDistributionService"),
  IDGenerator: Symbol.for("IDGenerator"),
  UuidGenerator: Symbol.for("UuidGenerator"),
  NanoIdGenerator: Symbol.for("NanoIdGenerator"),
  PaymentNotificationService: Symbol.for("PaymentNotificationService"),
  CancellationChargeService: Symbol.for("CancellationChargeService"),
  PaymentStrategies: Symbol.for("PaymentStrategies"),
  CouponValidationService: Symbol.for("CouponValidationService"),
  CouponUsageService: Symbol.for("CouponUsageService"),
  RideSearchQueueProducer: Symbol.for("RideSearchQueueProducer"),
  RideRequestTimeoutWorker: Symbol.for("RideRequestTimeoutWorker"),
  RideSearchDispatchService: Symbol.for("RideSearchDispatchService"),
  RideSearchQueue: Symbol.for("RideSearchQueue"),
  NotificationPersistenceService: Symbol.for("NotificationPersistenceService"),
  NotificationRealtimePublisher: Symbol.for("NotificationRealtimePublisher"),
  ChatRealtimeService: Symbol.for("ChatRealtimeService"),
  WorkerSocketBridge: Symbol.for("WorkerSocketBridge"),
  FutureRideExpiryService: Symbol.for("FutureRideExpiryService"),
  FutureRideExpiryQueue: Symbol.for("FutureRideExpiryQueue"),
  FutureRideExpiryWorker: Symbol.for("FutureRideExpiryWorker"),

  //Event
  EventBus: Symbol.for("EventBus"),
  ChatEventBus: Symbol.for("ChatEventBus"),
  CouponUsageOnPaymentSucceededHandler: Symbol.for(
    "CouponUsageOnPaymentSucceededHandler",
  ),
  CouponUsageOnPaymentCashConfirmedHandler: Symbol.for(
    "CouponUsageOnPaymentCashConfirmedHandler",
  ),

  // Adapters
  CryptoAdapter: Symbol.for("CryptoAdapter"),

  // Use Cases - Auth
  LoginUseCase: Symbol.for("LoginUseCase"),
  LogoutUseCase: Symbol.for("LogoutUseCase"),
  RefreshTokenUseCase: Symbol.for("RefreshTokenUseCase"),
  SignupRequestUseCase: Symbol.for("SignupRequestUseCase"),
  SignupVerifyUseCase: Symbol.for("SignupVerifyUseCase"),
  ForgotPasswordRequestUseCase: Symbol.for("ForgotPasswordRequestUseCase"),
  ForgotPasswordVerifyUseCase: Symbol.for("ForgotPasswordVerifyUseCase"),
  UpdatePasswordUseCase: Symbol.for("UpdatePasswordUseCase"),
  ResendOtpUseCase: Symbol.for("ResendOtpUseCase"),
  GetCurrentUserUseCase: Symbol.for("GetCurrentUserUseCase"),
  GoogleLoginUseCase: Symbol.for("GoogleLoginUseCase"),
  GetGoogleAuthUrlUseCase: Symbol.for("GetGoogleAuthUrlUseCase"),

  // Use Cases - Admin Users
  GetUsersUseCase: Symbol.for("GetUsersUseCase"),
  UpdateUserStatusUseCase: Symbol.for("UpdateUserStatusUseCase"),
  GetUserProfileDetailsUseCase: Symbol.for("GetUserProfileDetailsUseCase"),

  // Use Cases - Admin Drivers
  GetDriversUseCase: Symbol.for("GetDriversUseCase"),
  DriverActionUseCase: Symbol.for("DriverActionUseCase"),
  GetDriverProfileUseCase: Symbol.for("GetDriverProfileUseCase"),
  GetKycRequestsUseCase: Symbol.for("GetKycRequestsUseCase"),
  UpdateKycStatusUseCase: Symbol.for("UpdateKycStatusUseCase"),
  GetKycRequestByIdUseCase: Symbol.for("GetKycRequestByIdUseCase"),
  KycSubmissionUseCase: Symbol.for("KycSubmissionUseCase"),
  UpdateDriverKycStatusUseCase: Symbol.for("UpdateDriverKycStatusUseCase"),

  // Use Cases - Admin Ride
  GetAdminRidesUseCase: Symbol.for("GetAdminRidesUseCase"),
  ApprovePayoutUseCase: Symbol.for("ApprovePayoutUseCase"),
  RejectPayoutUseCase: Symbol.for("RejectPayoutUseCase"),
  GetAdminPayoutsUseCase: Symbol.for("GetAdminPayoutsUseCase"),

  CreateCouponUseCase: Symbol.for("CreateCouponUseCase"),
  EditCouponUseCase: Symbol.for("EditCouponUseCase"),
  GetAdminCouponsUseCase: Symbol.for("GetAdminCouponsUseCase"),
  GetAdminRatingsUseCase: Symbol.for("GetAdminRatingsUseCase"),
  GetAdminTransactionsUseCase: Symbol.for("GetAdminTransactionsUseCase"),
  GetAdminRideByIdUseCase: Symbol.for("GetAdminRideByIdUseCase"),
  GetAdminWalletUseCase: Symbol.for("GetAdminWalletUseCase"),

  //Use Cases - Admin status
  GetAdminUserStatsUseCase: Symbol.for("GetAdminUserStatsUseCase"),
  GetAdminRideStatsUseCase: Symbol.for("GetAdminRideStatsUseCase"),
  GetAdminDriverStatsUseCase: Symbol.for("GetAdminDriverStatsUseCase"),

  // Use Cases - Driver
  RegisterDriverUseCase: Symbol.for("RegisterDriverUseCase"),
  UpdateDriverProfileUseCase: Symbol.for("UpdateDriverProfileUseCase"),
  SubmitKYCUseCase: Symbol.for("SubmitKYCUseCase"),
  GetKYCStatusUseCase: Symbol.for("GetKYCStatusUseCase"),
  GetDriverDashboardUseCase: Symbol.for("GetDriverDashboardUseCase"),
  GetDriverStatusUseCase: Symbol.for("GetDriverStatusUseCase"),
  GetDriverDetailedProfileUseCase: Symbol.for(
    "GetDriverDetailedProfileUseCase",
  ),
  SendRideRequestUseCase: Symbol.for("SendRideRequestUseCase"),
  ScheduleRecurringAvailabilityUseCase: Symbol.for(
    "ScheduleRecurringAvailabilityUseCase",
  ),
  AddAvailabilityExceptionUseCase: Symbol.for(
    "AddAvailabilityExceptionUseCase",
  ),
  EditAvailabilityExceptionUseCase: Symbol.for(
    "EditAvailabilityExceptionUseCase",
  ),
  RemoveAvailabilityExceptionUseCase: Symbol.for(
    "RemoveAvailabilityExceptionUseCase",
  ),
  AcceptRideRequestUseCase: Symbol.for("AcceptRideRequestUseCase"),
  RejectRideRequestUseCase: Symbol.for("RejectRideRequestUseCase"),
  GetPendingRideRequestsUseCase: Symbol.for("GetPendingRideRequestsUseCase"),
  GetDriverRidesUseCase: Symbol.for("GetDriverRidesUseCase"),
  GetDriverRideByIdUseCase: Symbol.for("GetDriverRideByIdUseCase"),
  MarkRideAsArrivedUseCase: Symbol.for("MarkRideAsArrivedUseCase"),
  MarkRideAsStartedUseCase: Symbol.for("MarkRideAsStartedUseCase"),
  MarkRideAsCompletedUseCase: Symbol.for("MarkRideAsCompletedUseCase"),
  RequestPayoutUseCase: Symbol.for("RequestPayoutUseCase"),
  GetDriverPayoutsUseCase: Symbol.for("GetDriverPayoutsUseCase"),
  GetDriverWalletUseCase: Symbol.for("GetDriverWalletUseCase"),
  DriverCancelRideUseCase: Symbol.for("DriverCancelRideUseCase"),
  GetDriverStatsUseCase: Symbol.for("GetDriverStatsUseCase"),

  // Use Cases - User
  GetUserProfileUseCase: Symbol.for("GetUserProfileUseCase"),
  UpdateUserProfileUseCase: Symbol.for("UpdateUserProfileUseCase"),
  RegisterUserAsDriverUseCase: Symbol.for("RegisterUserAsDriverUseCase"),
  FindNearbyDriversUseCase: Symbol.for("FindNearbyDriversUseCase"),
  AutoSearchAndSendRideRequestUseCase: Symbol.for(
    "AutoSearchAndSendRideRequestUseCase",
  ),
  CancelRideRequestsUseCase: Symbol.for("CancelRideRequestsUseCase"),
  GetUserRideByIdUseCase: Symbol.for("GetUserRideByIdUseCase"),
  GetUserRidesUseCase: Symbol.for("GetUserRidesUseCase"),
  CancelRideUseCase: Symbol.for("CancelRideUseCase"),
  RateDriverUseCase: Symbol.for("RateDriverUseCase"),
  ApplyCouponUseCase: Symbol.for("ApplyCouponUseCase"),
  GetUserCouponsUseCase: Symbol.for("GetUserCouponsUseCase"),
  RemoveCouponUseCase: Symbol.for("RemoveCouponUseCase"),
  GetUserStatsUseCase: Symbol.for("GetUserStatsUseCase"),
  ScheduleFutureRideRequestUseCase: Symbol.for(
    "ScheduleFutureRideRequestUseCase",
  ),
  CancelFutureRideRequestUseCase: Symbol.for("CancelFutureRideRequestUseCase"),

  //Use Cases - Chat
  CreateRideChatRoomUseCase: Symbol.for("CreateRideChatRoomUseCase"),
  GetRideChatRoomUseCase: Symbol.for("GetRideChatRoomUseCase"),
  GetChatMessagesUseCase: Symbol.for("GetChatMessagesUseCase"),
  SendChatMessageUseCase: Symbol.for("SendChatMessageUseCase"),
  EditChatMessageUseCase: Symbol.for("EditChatMessageUseCase"),
  DeleteChatMessageUseCase: Symbol.for("DeleteChatMessageUseCase"),
  MarkChatMessagesReadUseCase: Symbol.for("MarkChatMessagesReadUseCase"),

  // Use Cases - File
  UploadFileUseCase: Symbol.for("UploadFileUseCase"),
  GetUserFilesUseCase: Symbol.for("GetUserFilesUseCase"),
  DeleteFileUseCase: Symbol.for("DeleteFileUseCase"),
  UpdateProfilePictureUseCase: Symbol.for("UpdateProfilePictureUseCase"),

  // Use Cases - Notifications
  NotificationRepository: Symbol.for("NotificationRepository"),
  GetNotificationsUseCase: Symbol.for("GetNotificationsUseCase"),
  MarkNotificationsReadUseCase: Symbol.for("MarkNotificationsReadUseCase"),
  CreateNotificationUseCase: Symbol.for("CreateNotificationUseCase"),

  // Use Cases - Payment
  InitiatePaymentUseCase: Symbol.for("InitiatePaymentUseCase"),
  VerifyPaymentUseCase: Symbol.for("VerifyPaymentUseCase"),
  ConfirmCashPaymentUseCase: Symbol.for("ConfirmCashPaymentUseCase"),
  MarkPaymentFailedUseCase: Symbol.for("MarkPaymentFailedUseCase"),

  // Use Cases Driver Availability
  ScheduleAvailabilityUseCase: Symbol.for("ScheduleAvailabilityUseCase"),
  UpdateAvailabilityStatusUseCase: Symbol.for(
    "UpdateAvailabilityStatusUseCase",
  ),
  UpdateDriverLocationUseCase: Symbol.for("UpdateDriverLocationUseCase"),

  // Controllers
  LoginController: Symbol.for("LoginController"),
  SignupController: Symbol.for("SignupController"),
  OtpController: Symbol.for("OtpController"),
  PasswordController: Symbol.for("PasswordController"),
  SocialAuthController: Symbol.for("SocialAuthController"),
  UserAuthController: Symbol.for("UserAuthController"),
  // AuthUserController: Symbol.for("AuthUserController"),
  TokenController: Symbol.for("TokenController"),
  AdminUserController: Symbol.for("AdminUserController"),
  AdminDriverController: Symbol.for("AdminDriverController"),
  DriverController: Symbol.for("DriverController"),
  UserProfileController: Symbol.for("UserProfileController"),
  FileController: Symbol.for("FileController"),
  DriverAvailabilityController: Symbol.for("DriverAvailabilityController"),
  DriverSearchController: Symbol.for("DriverSearchController"),
  RideController: Symbol.for("RideController"),
  AutoRideController: Symbol.for("AutoRideController"),
  DriverRideController: Symbol.for("DriverRideController"),
  NotificationController: Symbol.for("NotificationController"),
  AdminRideController: Symbol.for("AdminRideController"),
  DriverRideActionsController: Symbol.for("DriverRideActionsController"),
  PaymentController: Symbol.for("PaymentController"),
  DriverPayoutController: Symbol.for("DriverPayoutController"),
  AdminPayoutController: Symbol.for("AdminPayoutController"),
  DriverWalletController: Symbol.for("DriverWalletController"),
  AdminCouponController: Symbol.for("AdminCouponController"),
  CouponController: Symbol.for("CouponController"),
  AdminTransactionController: Symbol.for("AdminTransactionController"),
  AdminWalletController: Symbol.for("AdminWalletController"),
  ChatRoomController: Symbol.for("ChatRoomController"),
  ChatMessageController: Symbol.for("ChatMessageController"),
  AdminStatsController: Symbol.for("AdminStatsController"),
  DriverStatsController: Symbol.for("DriverStatsController"),
};
