export enum ErrorType {
  CLIENT_ERROR = "CLIENT_ERROR",

  SERVER_ERROR = "SERVER_ERROR",

  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",

  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",

  VALIDATION_ERROR = "VALIDATION_ERROR",

  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",

  CONFLICT_ERROR = "CONFLICT_ERROR",

  NETWORK_ERROR = "NETWORK_ERROR",

  DATABASE_ERROR = "DATABASE_ERROR",

  BUSINESS_ERROR = "BUSINESS_ERROR",
}
